### ISSUE TITLE
Build Errors in Libscout-master project

### ISSUE THREAD

**Issue by kaluva** [reddr/LibScout#12]
I'm getting build errors as soon as I open the project in eclipse. Please find the below screenshot and help me in fixing them.

![libscout_build_errors](https://user-images.githubusercontent.com/6791564/41510175-7ff87f4c-727d-11e8-84c1-aa3b639a5647.PNG)

**Comment by reddr** [comment]
Make sure you add an Android SDK .jar to your dependencies. See instructions at LibScout 101 in the Readme.
