### ISSUE TITLE
Command line parsing failed:

### ISSUE THREAD

**Issue by Kantha4security** [reddr/LibScout#13]
Unable to execute the jar file, please help me, if there I did any wrong in below steps.

1. Generated .jar using eclipse
2. copied android API 28 jar file to Libscout\lib\android.jar
3. downloaded profiles from https://github.com/reddr/LibScout-Profiles.git and extracted to profiles directory. 
4. Copied an apk to the Libscout\apk\123.apk directory
5. Tried the below command
          _**java -jar build\LibScout.jar --opmode match -a lib\android.jar -p profiles\profiles\md5\Android -d log $apk\123.apk**_
6. I'm getting an error as below
_**Command line parsing failed:
Argument is no valid file or directory!
usage: LibScout --opmode match -a <path-to-android.jar> <options> $path-to-app(-dir)**_

![command](https://user-images.githubusercontent.com/33095790/41511720-1f587b52-729a-11e8-8ac7-145574768539.jpg)
![lib](https://user-images.githubusercontent.com/33095790/41511723-23a436a6-729a-11e8-8ced-161b7f0ca066.jpg)
![android](https://user-images.githubusercontent.com/33095790/41511725-32ae4d44-729a-11e8-8710-8778df29549a.jpg)

**Comment by reddr** [comment]
It does not find the apk. Remove the $ sign from the path, i.e. correct path should be apk\123.apk
