### ISSUE TITLE
Multi-dex APKs not completely processed

### ISSUE THREAD

**Issue by Szilard95** [reddr/LibScout#19]
Hi,

I'm trying to use LibScout with an APK containing 100+ dex files. I found out (after increasing the log levels) that currently only the first 10 classes.dex files are processed, resulting in an incomplete package tree for APKs with 10+ dex files.
The cause of this is the regex in the WALA code: `classes[1-9]{0,1}\\.dex`.
I think it might be a good idea to get rid of this limitation.

I changed the regex in the `DexFileModule.class` file to `classes[0-9]{0,9}\\.dex` and every dex file is successfully processed now. But now I get an exception when exporting to JSON:
```
ERROR TplCLI                    : [FATAL EXCEPTION] analysis aborted: null
ERROR TplCLI                    : java.lang.NullPointerException
        at de.infsec.tpl.profile.ProfileMatch$Export.<init>(ProfileMatch.java:120)
        at de.infsec.tpl.profile.ProfileMatch.export(ProfileMatch.java:132)
        at de.infsec.tpl.stats.AppStats$Export.<init>(AppStats.java:130)
        at de.infsec.tpl.stats.AppStats.export(AppStats.java:48)
        at de.infsec.tpl.utils.Utils.obj2JsonFile(Utils.java:487)
        at de.infsec.tpl.LibraryIdentifier.identifyLibraries(LibraryIdentifier.java:207)
        at de.infsec.tpl.TplCLI.main(TplCLI.java:155)
```

Also, I know that you use Joana's WALA fork but any plans to publish your patches?

**Comment by reddr** [comment]
Ah, I anticipated that this would happen at some point. I will remove this limitation. 

As for the Export error, do you have an apk or l <package name, versioncode> that I can test?

Regarding the WALA patches, yes I think it's a good idea to make them available. I will also open a new issue regarding checking LibScout's WALA version against WALA master to see whether patches are already included or can be merged. In the longterm it's certainly preferable to not rely on a custom fork (see also discussion here: https://github.com/reddr/LibScout/issues/16).

**Comment by Szilard95** [comment]
Unfortunately I can't share the apk, but thanks anyway.

**Comment by reddr** [comment]
If you can provide a similar/stripped apk with many dex files that trigger this exception, I can have a look into the problem, otherwise it's pure guessing.

**Comment by reddr** [comment]
Hi @Szilard95, I just upgraded LibScout to use the latest version of WALA/dexlib2.
There shouldn't be any more restrictions on the number of dex files. Can you give it a try?

**Comment by reddr** [comment]
I justed tested it on an app with 10 .dex files w/o problems.

**Comment by reddr** [comment]
Ok no more reply here.  10+ dex files work now and probably the NPE in the profile export was fixed with the commit https://github.com/reddr/LibScout/commit/88ec8207318ca16aba395c5a17dd1ed964db8fc5
