### ISSUE TITLE
output json format

### ISSUE THREAD

**Issue by A-AFTAHI** [reddr/LibScout#21]
i cloned LibScout after last commit and when running the command:
**java -jar build/libs/LibScout.jar -o match -a lib/android-23.jar -p profiles/ -j ./json/ app-release.apk**
the json files are no more created. i already checked privileges issues and gives writing privileges to all for json folder and subfolders and still not working. 
i tried it with differents androif-sdk versions.

**Comment by reddr** [comment]
I just cloned master to a fresh directory, but I could not reproduce the problem.
JSON output is created both with -j and -j <dirname>. 

Did you check the log output? Does the second-to-last line say:
`Write app stats to JSON (dir: ./json)`

**Comment by reddr** [comment]
Closing, as there is no more answer for more than a month.
