### ISSUE TITLE
Unreadable character in the result of the analyze - Windows

### ISSUE THREAD

**Issue by Drjacky** [reddr/LibScout#22]
I've run my desirable command on my windows 64-bit machine, and got such this result:
> 19:30:58 INFO  PackageTree               :     ظ¤é   ظ¤é   ظ¤£ظ¤ظ¤ d (3)

A related conversation is: [here](https://github.com/reddr/LibScout/issues/17#issuecomment-442951113)

**Comment by reddr** [comment]
I don't have a Windows machine at hand, so could you please try the following:
Replace the print function in 
   https://github.com/reddr/LibScout/blob/master/src/de/infsec/tpl/pkg/PackageTree.java (line 75ff)
with 
```
private void print(String prefix, boolean isTail, boolean includeClazzCount) {
    logger.info(prefix + (isTail ? "\u2514\u2500\u2500 " : "\u251C\u2500\u2500 ") + name + (includeClazzCount && clazzCount > 0? " (" + clazzCount + ")" : ""));

    for (int i = 0; i < childs.size(); i++) {
        childs.get(i).print(prefix + (isTail ? "    " : "\u2502   "), i == childs.size()-1, includeClazzCount);
    }
 }
```
recompile and check whether the box-drawing characters are rendered correctly.

**Comment by Drjacky** [comment]
@reddr I've built with the mentioned snippet code but didn't solve.
Now it shows question mark:
 > 11:32:12 INFO  PackageTree               :     ??? dagger (1)

**Comment by reddr** [comment]
@Drjacky  It seems that your console cannot render unicode characters. One reason could be the used font. StackOverflow has a lot of topics on Unicode and Windows console.

A visually less pleasing option that simply uses ASCII characters should also do the job, i.e.

```
private void print(String prefix, boolean isTail, boolean includeClazzCount) {
  logger.info(prefix + (isTail ? "|___ " : "|--- ") + name + (includeClazzCount && clazzCount > 0? " (" + clazzCount + ")" : ""));

  for (int i = 0; i < childs.size(); i++) {
    childs.get(i).print(prefix + (isTail ? "    " : "|   "), i == childs.size()-1, includeClazzCount);
  }
}
```

**Comment by Drjacky** [comment]
Now, it seems okay:
 > 20:09:14 INFO  PackageTree               :     |
20:09:14 INFO  PackageTree               :     |--- dagger (1)

I've sent a [pull request](https://github.com/reddr/LibScout/pull/25).
