### ISSUE TITLE
Facebook libraries are always detected

### ISSUE THREAD

**Issue by RobertHamilton1415** [reddr/LibScout#28]
Libscout seems to be detecting Facebook libraries for every application - including the empty project template within Android Studio 3.2.1.
[libscout.txt](https://github.com/reddr/LibScout/files/3117881/libscout.txt)

**Comment by reddr** [comment]
The problem with the Facebook lib is that starting from 4.27, FB split the monolithic SDK into multiple ones, i.e. Facebook-Core, Facebook-Login, etc. If you look at the repos like Maven Central, you can still see that the original FB lib has not been discontinued, but instead has changed to simply being a wrapper for all the new libraries. AFAIK, internally it's no more than a simple loader. It's propably exactly one method with a generic signature and that's the reason why it is "detected" in any app.

The workaround is pretty simple, delete the profiles for the monolithic Facebook SDK newer than 4.26.
If you work with the library scraper, you can simply delete the respective directories to prevent profiling of these versions.

**Comment by RobertHamilton1415** [comment]
Cheers, I'll try that

**Comment by RobertHamilton1415** [comment]
Thanks, that solved it
