### ISSUE TITLE
 [FATAL EXCEPTION] analysis aborted: null

### ISSUE THREAD

**Issue by kydahe** [reddr/LibScout#30]
Hi, when I use Library Detection (-o match), It seems appear some errors.

I input the command:
`
java -jar ./build/libs/LibScout.jar -o match -p ./profiles/Cloud -a ./sdk/android.jar -j ./json app.apk 
`
The profiles are generated by myself, from some SDK jar files. 
I also change the asserts/library.xml.

And then errors appear:
the command output is 
`
11:07:08 DEBUG HashTree                  : Generate hash tree..

11:07:14 DEBUG HashTree                  :     - generated 698 package hashes.

11:07:14 DEBUG HashTree                  :     - generated 8939 clazz hashes.

11:07:14 DEBUG HashTree                  :     - generated 60936 method hashes.

11:07:14 DEBUG HashTree                  :     => Library Hash: b66cf0802b150b4e24eac7a566f61709

11:07:14 INFO  AppProfile                : - generated app hash trees (in 5 sec, 636 ms)

11:07:14 INFO  AppProfile                : 

11:07:14 INFO  LibraryIdentifier         : = Scan for library root packages (heuristic) =

11:07:14 INFO  LibraryIdentifier         : 

11:07:14 INFO  LibraryIdentifier         : = Match profiles =

11:07:14 ERROR TplCLI                    : [FATAL EXCEPTION] analysis aborted: null

11:07:14 ERROR TplCLI                    : java.lang.NullPointerException
	at de.infsec.tpl.modules.libmatch.LibraryIdentifier.identifyLibraries(LibraryIdentifier.java:183)
	at de.infsec.tpl.modules.libmatch.LibraryIdentifier.run(LibraryIdentifier.java:84)
	at de.infsec.tpl.TplCLI.main(TplCLI.java:141)
`
Please help me why does this issue occur and how to solve this issue?

**Comment by reddr** [comment]
LibraryIdentifier.java:183 checks whether the currently processed lib version is the current one or an older version. Thus, it will be related to the profiles you generated. These checks are not very robust, to be honest, and rely on Library name and version you entered in the library.xml files.

Here a few things you can check:
- If you have multiple versions of the same library, make sure the name in the library.xml files do exactly match, before generating the profiles.
- For debugging, increase the log verboseness for the LibraryIdentifier class from "info" to *debug* or *trace* and check what LibScout has read from your files. You can easily change this in the config/logback.xml file (line 7). No need to recompile.

**Comment by kydahe** [comment]
Thank you for your reply!! 
The problem has been solved. It seems that I didn't add the version info.
But the results seem have some mistakes. I will try to check it.
Thanks again!
