### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by A-AFTAHI** [reddr/LibScout#7]
isn't possible to update the database when running 
java -jar build/LibScout.jar -o db -p profiles/md5/ -s stats/
because i got this error message
12:19:40 INFO  SQLStats                  : Generate DB from stats mode!
12:19:40 INFO  SQLStats                  :     Loaded 4965 profiles from disk
12:19:40 WARN  SQLStats                  : DB file appStats.sqlite exists! -- No updates will be performed -Abort!
so i have to delete the existant file each time i wanna run the command

**Comment by reddr** [comment]
Yes, a real DB update routine is currently missing. Therefore, it needs to be rebuild everytime for now.

**Comment by reddr** [comment]
I removed the deprecated DB mode in the last commit. The json mode is now recommended. The json files can then be post-processed arbitrarily.
