### ISSUE TITLE
json format

### ISSUE THREAD

**Issue by A-AFTAHI** [reddr/LibScout#8]
when i run LibSout using -j option:
 java -jar build/LibScout.jar -o match -a lib/android-23.jar -p profiles/md5/ -j json/  -m  /root/Downloads/dgi_proguard.apk

inside the json/ folder i found the json files stored in other folders arborescence, i wonder is it based on the application package?

**Comment by reddr** [comment]
Yes, the results are stored in subfolders following the app packagename, i.e. com.facebook.katana will be stored in <json-folder>/com/facebook/katana. This has been done better manage large-scale evaluations.
I will clarify the documentation, thanks for the catch.

**Comment by reddr** [comment]
Done, see 3ac112c8e3d48d0c460c2497ad830ca44eafae0c
